version: '3.0'

services:
  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
     # volumes:
         # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
       - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
       - POSTGRES_USER=airflow
       - POSTGRES_PASSWORD=airflow
       - POSTGRES_DB=airflow
    command: scheduler

  worker:
    build: .
    restart: always
    ports:
      - "8793:8793"
    depends_on:
      - scheduler
      - redis
    # volumes:
       # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    command: worker

  flower:
    build: .
    restart: always
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "5555:5555"
    command: flower

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

volumes:
    postgresData:
