version: '3.0'

services:
  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
     - "8080:8080"
    command: webserver

  scheduler:
    build: .
    restart: always
    depends_on:
      - webserver
     # volumes:
         # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
       - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
       - POSTGRES_USER=airflow
       - POSTGRES_PASSWORD=airflow
       - POSTGRES_DB=airflow
    command: scheduler

  worker:
    build: .
    restart: always
    depends_on:
       - scheduler
    # volumes:
       # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
       - POSTGRES_USER=airflow
       - POSTGRES_PASSWORD=airflow
       - POSTGRES_DB=airflow
    command: worker

  flower:
    build: .
    restart: always
    depends_on:
      - redis
      - scheduler
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  redis:
    image: 'redis:3.2.9'

  postgres:
    image: postgres:9.6
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

volumes:
    postgresData:
