version: '3.0'

services:
  webserver:
    build: .
    restart: always
    links:
      - postgres:postgres
      - redis:redis
      - worker:worker
      - scheduler:scheduler
    # depends_on:
    #   - postgres
    #   - redis
    ports:
     - "8080:8080"
    command: webserver

  scheduler:
    build: .
    restart: always
    links:
      - postgres:postgres
      - redis:redis
    # depends_on:
      # - webserver
     # volumes:
         # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
       - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
       - POSTGRES_USER=airflow
       - POSTGRES_PASSWORD=airflow
       - POSTGRES_DB=airflow
    command: scheduler

  worker:
    build: .
    restart: always
    links:
      - postgres:postgres
      - redis:redis
    # depends_on:
      #  - scheduler
    # volumes:
       # - ~/docker-airflow/dags:/usr/local/airflow/dags
    environment:
       - POSTGRES_USER=airflow
       - POSTGRES_PASSWORD=airflow
       - POSTGRES_DB=airflow
    command: worker

  flower:
    build: .
    restart: always
    links:
      - redis:redis
    # depends_on:
    #   - redis
    #   - scheduler
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  redis:
    image: 'redis:3.2.9'
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow

volumes:
    postgresData:
